-- H2 Test Schema for CouponSystem

CREATE TABLE IF NOT EXISTS companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(48),
    PASSWORD VARCHAR(60),
    FAILED_LOGIN_ATTEMPTS INT DEFAULT 0 NOT NULL,
    ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE NOT NULL,
    LOCKED_UNTIL TIMESTAMP NULL,
    LAST_FAILED_LOGIN TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(48),
    LAST_NAME VARCHAR(48),
    EMAIL VARCHAR(48),
    PASSWORD VARCHAR(60),
    FAILED_LOGIN_ATTEMPTS INT DEFAULT 0 NOT NULL,
    ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE NOT NULL,
    LOCKED_UNTIL TIMESTAMP NULL,
    LAST_FAILED_LOGIN TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS coupons (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID INT,
    CATEGORY VARCHAR(48),
    TITLE VARCHAR(48),
    DESCRIPTION VARCHAR(48),
    START_DATE DATE,
    END_DATE DATE,
    AMOUNT INT,
    PRICE DOUBLE,
    IMAGE VARCHAR(48),
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers_vs_coupons (
    CUSTOMER_ID INT NOT NULL,
    COUPON_ID INT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, COUPON_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (COUPON_ID) REFERENCES coupons(ID) ON DELETE CASCADE
);
