-- H2 Test Schema for CouponSystem

CREATE TABLE IF NOT EXISTS categories (
    ID INT PRIMARY KEY,
    NAME VARCHAR(48)
);

INSERT INTO categories (ID, NAME) VALUES
(10, 'SKYING'),
(20, 'SKY_DIVING'),
(30, 'FANCY_RESTAURANT'),
(40, 'ALL_INCLUSIVE_VACATION');

CREATE TABLE IF NOT EXISTS companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(48),
    EMAIL VARCHAR(48),
    PASSWORD VARCHAR(48)
);

CREATE TABLE IF NOT EXISTS customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(48),
    LAST_NAME VARCHAR(48),
    EMAIL VARCHAR(48),
    PASSWORD VARCHAR(48)
);

CREATE TABLE IF NOT EXISTS coupons (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID INT,
    CATEGORY_ID INT,
    TITLE VARCHAR(48),
    DESCRIPTION VARCHAR(48),
    START_DATE DATE,
    END_DATE DATE,
    AMOUNT INT,
    PRICE DOUBLE,
    IMAGE VARCHAR(48),
    FOREIGN KEY (COMPANY_ID) REFERENCES companies(ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES categories(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers_vs_coupons (
    CUSTOMER_ID INT NOT NULL,
    COUPON_ID INT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, COUPON_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE,
    FOREIGN KEY (COUPON_ID) REFERENCES coupons(ID) ON DELETE CASCADE
);
